### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by talhazengin** [causal-agent/scraper#122]
Is there a way to disable logging? I don't want any third-party library log messages in my application even if i set log level to Trace.

**Comment by adamreichold** [comment]
Depending on which logger implementation you use, you can usually define log levels on a per-module basis, for example `env_logger` supports a `<module>=<level>` syntax. Using this technique, you can either limit enabling trace logging to the module you are currently investigating or alternatively suppress the logs from dependencies you are not interested in.

**Comment by talhazengin** [comment]
Understood, thank you.
