### ISSUE TITLE
How to select in pairs?

### ISSUE THREAD

**Issue by extf33** [causal-agent/scraper#127]
How to select only `pre.CCC` with "Hello, Rust!" immediately before it, in the code below?

```html
<section id="AAA">
    <p class="BBB">Hello, Rust!</p>
    <pre class="CCC">...</pre> ----------> O
    <p>...</p>
    <pre class="CCC">...</pre> ----------> X
</section>
```

**Comment by adamreichold** [comment]
Did you try `p.BBB + pre.CCC` which selects the `pre.CC` if it is immediately preceded by `p.BBB`? If you try select based on `Hello, Rust!`, then this not yet possible with CSS selectors AFAIK.
