### ISSUE TITLE
same element?

### ISSUE THREAD

**Issue by asyncins** [causal-agent/scraper#138]
element_1 is `<div>causal-agent</div>`

element_2 is `<p>scraper</p>`

element_3 is `<div>causal-agent</div>`

we need this
```
if same(element_1, element_3){
  println!("true")
}else{
  println!("false")
}
```

How to ???

**Comment by adamreichold** [comment]
Defining what "same" means is usually specific to a use case. In the example you presented, a helper function which checks that `element.value().name()` and `element.text()` (possibly after trimming) match might be sufficient.

**Comment by asyncins** [comment]
> Defining what "same" means is usually specific to a use case. In the example you presented, a helper function which checks that `element.value().name()` and `element.text()` (possibly after trimming) match might be sufficient.

the "same" means  they are the same block of memory，not text, not name, not index, not tag

**Comment by adamreichold** [comment]
Then compare pointers `std::ptr::eq(&element_1, &element_3)`.
