### ISSUE TITLE
Allow `Selector` to be const-creatable

### ISSUE THREAD

**Issue by conqp** [causal-agent/scraper#141]
Currently we cannot create `const SELECTOR: Selector = ...` object, due to `Selector::parse` not being const.
This in turn would require `cssparser::Tokenizer::new()` and `cssparser::Tokenizer::with_first_line_number()` to be const as well.
I think that this would be possible to do.

**Comment by adamreichold** [comment]
I am highly sceptical this will be possible soon as this would require things like [`selectors::parser::SelectorList::parse`](https://docs.rs/selectors/latest/selectors/parser/struct.SelectorList.html#method.parse) to be const.

**Comment by conqp** [comment]
Probably. I'm currently using `once_cell::sync::Lazy` to work around this limitation.

**Comment by cfvescovo** [comment]
OnceCell is now part of the standard library: https://github.com/rust-lang/rfcs/pull/2788
I think this should be considered the solution to this issue, since we cannot make Selector const-creatable
