### ISSUE TITLE
Support for `:has()` selector

### ISSUE THREAD

**Issue by 124C41p** [causal-agent/scraper#169]
Hi, do you plan to support [the `:has()` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has)? To my understanding, this css keyword is needed for selecting objects based on the parent of another known object.

Consider the following example:
```html
<div>
    <div id="foo">
        Hi There!
    </div>
</div>
<ul>
    <li>first</li>
    <li>second</li>
    <li>third</li>
</ul>
```
In order to select the second list item, I would like to use the following selector:

```rust
let selector = Selector::parse("div:has(div#foo) + ul > li:nth-child(2)").unwrap();
```

This line however panics as of `scraper` version 0.18.1.

**Comment by adamreichold** [comment]
I think this is still missing support in our upstream dependency [`selectors`](https://crates.io/crates/selectors) dependency, at least in the version published on crates.io.

**Comment by cyqsimon** [comment]
+1. I'm trying to scrape Wikipedia, which has this sort of nesting. [For example](https://en.wikipedia.org/w/index.php?title=List_of_TCP_and_UDP_port_numbers):

```html
<h2>
  <span class="mw-headline" id="Registered_ports">Registered ports</span>
  <!-- ... -->
</h2>
```

This selector: `h2:has(#Registered_ports) ~ .wikitable.sortable` would pick the first table after this `h2`, which is a good way to locate the content in lieu of a distinctive id/class on the table itself.

**Comment by nicoburns** [comment]
From what I can see selectors 0.25 (published to crates.io) does have `:has` support. See https://docs.rs/selectors/latest/selectors/parser/enum.Component.html#variant.Has

**Comment by nathaniel-daniel** [comment]
https://github.com/servo/servo/issues/25133

**Comment by jameshurst** [comment]
I had taken a look into adding `:is()` support and it seems like both `:is()` and `:has()` are already supported by `selectors`. The [`Parser`](https://github.com/causal-agent/scraper/blob/v0.19.0/src/selector.rs#L86) impl needs to enable support by implementing `parse_is_and_where` and `parse_has`.

```rust
fn parse_is_and_where(&self) -> bool {
    true
}

fn parse_has(&self) -> bool {
    true
}
```

@causal-agent Should it be safe to enable support for these selectors? I can make a PR with these changes unless these selectors are not enabled for a reason.

**Comment by adamreichold** [comment]
> The [Parser](https://github.com/causal-agent/scraper/blob/v0.19.0/src/selector.rs#L86) impl needs to enable support by implementing parse_is_and_where and parse_has.

Thank you for looking into this!

> Should it be safe to enable support for these selectors? I can make a PR with these changes unless these selectors are not enabled for a reason.

I think only tests will answer that. Please open a PR, ideally including a test case. I can try to then also give it a spin in a code base containing a pretty diverse set of scrapers and see if anything breaks that is not caught by the tests here.

**Comment by cfvescovo** [comment]
@jameshurst when your PR is ready, tag me. I will run some tests and review it ASAP.

**Comment by cfvescovo** [comment]
I opened a PR addressing this, have a look
