### ISSUE TITLE
How do i remove certain tags/nodes before selecting a text?

### ISSUE THREAD

**Issue by naveenann** [causal-agent/scraper#26]
When we have few tags that need to be removed before selecting a tag for example

```
fn main() {
let selector = Selector::parse("body").unwrap();
    let html = r#"
    <!DOCTYPE html>
   <body>
   Hello World
   <script type="application/json" data-selector="settings-json">
   {"test":"json"}
   </script>
   </body>
"#;
    let document = Html::parse_document(html);
    let body = document.select(&selector).next().unwrap();
    let text = body.text().collect::<Vec<_>>();
    println!("{:?}", text);
}
```
Output

`["\n   Hello World\n   ", "\n   {\"test\":\"json\"}\n   ", "\n   \n"]`

The output will have the value from the script tags, Is there any way we can remove those?

**Comment by programble** [comment]
The `Text` iterator is quite a simple wrapper around the `Traverse` operator: <https://github.com/programble/scraper/blob/master/src/element_ref/mod.rs#L107-L126>. I think it should be possible to write a loop over `Traverse` directly which avoids `script` elements. That's all I can think of since selectors can't select text nodes.

**Comment by Boscop** [comment]
@causal-agent Is it possible to exclude all children of the node for traversal / getting its text?

**Comment by hydrocortisone** [comment]
@Boscop have the same issue right now...:-)

**Comment by hydrocortisone** [comment]
For markup like this:
```
<a href="" class="pagination__link button button--text">
    <span class="sr-only">Page</span>
    333
</a>
```

I wrote following code to extract 333: 
```
let value = extractor.extract_inner_html(&selectors);
let index = value.rfind('\n').unwrap();
let slice = &value[index..];
```

I can also use last '>' symbol as base.

I hope it will be helpful...:)

**Comment by hydrocortisone** [comment]
@causal-agent Hi! Could you suggest any possibilities to do inner_text method like for example in jquery using html5ever? I can probably help with implementation...Just this html5ever is absolute dark forest for me...

**Comment by alexlee85** [comment]
just use ElementRef to get child text node.
```rust
let only_self_text = doc
    .select(&Selector::parse("button > span").unwrap())
    .next()
    .and_then(|item| item.first_child())
    .and_then(|t| t.value().as_text())
    .map(|t| t.text.to_string())
    .unwrap_or_default();
```
