### ISSUE TITLE
Looking for maintainer(s)

### ISSUE THREAD

**Issue by causal-agent** [causal-agent/scraper#36]
I haven't been actively using or developing this project for quite a while now and haven't had time to respond to new issues and PRs. I would like to find someone more qualified than me to continue maintenance and/or development of this project which seems to be quite popular. If anyone would like to help out, please comment here or send me an email.

**Comment by jparr721** [comment]
I am interested in helping! I intend to use this for work-related things and would love to get involved keeping it alive.

**Comment by firstprayer** [comment]
This seems to be a promising library. Happy to help if needed.

**Comment by mxork** [comment]
happy to help if needed.

**Comment by SirWindfield** [comment]
Using this inside of my scraper framework so I would love to help out as well!

**Comment by spegoraro** [comment]
Count me in too

**Comment by programble** [comment]
Thanks for the responses! In absence of any ideas on vetting or whatever, I'm going to just set branch protection and add collaborators.

Also a heads up, I think I'll be renaming my GitHub account soon, so an upcoming change in URL shouldn't be concerning.

**Comment by SirWindfield** [comment]
@causal-agent Is there a reason why the scraper.1 file has been uploaded to the repository? I have no clue what that file is and what its purpose is.

**Comment by causal-agent** [comment]
That is the manual page for the scraper bin utility.

**Comment by rtrevinnoc** [comment]
I can help too

**Comment by jakequade** [comment]
I'd love to maintain/contribute - this library is great.

**Comment by cfvescovo** [comment]
This is an extremely useful library! Count me in!

**Comment by Boscop** [comment]
Did you find a maintainer? :)

**Comment by apkrieg** [comment]
I'm willing to take over the project.

**Comment by fernandosoto138** [comment]
@causal-agent Willing to help here. Supporting @apkrieg

**Comment by seanpianka** [comment]
Perhaps someone can start a Discord and invite everyone?

**Comment by azzamsa** [comment]
Since there is no response from CasualAgent, Is someone already started a fork (perhaps with a new name) to continue the development?

**Comment by cfvescovo** [comment]
I have created a fork of this repo named [dissector](https://github.com/cfvescovo/dissector). I am currently working on:
- renaming the project
- updating the dependencies
- switching the Rust language version to 2021
- publishing the crate on [crates.io](https://crates.io)
After these steps I will start working on new features and overall improvements.

I am looking for contributors, if someone's willing to help write it here.

**Comment by causal-agent** [comment]
@cfvescovo if you're willing to do that work, I can give you commit access here and permission to publish the `scraper` crate (assuming I can figure out how). Sorry I haven't been paying attention to this. Without any development happening it's impossible to tell who needs access.

**Comment by cfvescovo** [comment]
@causal-agent Thank you! I will delete my fork and commit my changes to your repo.

**Comment by cfvescovo** [comment]
I think you can give other people publishing permissions on crates.io by using the - command `cargo owner`. Docs: [cargo reference - publishing crates](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner)

**Comment by causal-agent** [comment]
@cfvescovo I sent an owner invite through the crates.io interface

**Comment by cfvescovo** [comment]
Thank you. I have accepted your invite

**Comment by cfvescovo** [comment]
> Perhaps someone can start a Discord and invite everyone?

I have created a Gitter community for this repo. Link: [Gitter - scraper-rs community](https://gitter.im/scraper-rs/community)
