### ISSUE TITLE
Q: Combine selectors

### ISSUE THREAD

**Issue by oleid** [causal-agent/scraper#40]
Just discovered this care today, really nice!
One question though: Is it possible to combine selectors? 

I wrote some code today to extract content from a wordpress page. First selected the `<article>` tag, then all `<p>`. Which basically does the trick. Yet, titles and possibly images are missing.

So I was wondering, if it was _somehow_ possible to create a selector, which selects `p` | `h1` | `h2` and so on?

Or if that isn't possible, what would be the recommended approach?

**Comment by causal-agent** [comment]
The selector `p, h1, h2` matches any of the three elements.

**Comment by adamrmelnyk** [comment]
@causal-agent Do you mind if I open a PR to ad an example of this in the README? This question saved me a lot of time!

**Comment by causal-agent** [comment]
I don't think scraper's readme is the place to document CSS selector syntax.
