### ISSUE TITLE
can't select with ~ and *

### ISSUE THREAD

**Issue by aCLr** [causal-agent/scraper#50]
Greetings!
First of all I hope that you'll find maintainer because the library is awesome.

Unfortunatelly I can't use all possible attribute selectors:
```
fn main() {
    use scraper::{Html, Selector};

    let doc = Html::parse_fragment(r#"<a href="https://google.com""#);
    let sel = Selector::parse(r#"[href=~"goo"]"#).unwrap();
    println!("{:?}", doc.select(&sel).next());
}
```

The error is `ParseError { kind: Custom(BadValueInAttr(Delim('~'))), location: SourceLocation { line: 0, column: 7 } }`. And the same error appears with `[href=*"goo"]`.

**Comment by causal-agent** [comment]
Looks like it's `~=` rather than `=~` https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by aCLr** [comment]
Facepalm..
Ok, my bad. But...
```
fn main() {
    use scraper::{Html, Selector};

    let doc = Html::parse_fragment(r#"<a href="https://google.com""#);
    let sel = Selector::parse(r#"[href*="google"]"#).unwrap();
    println!("{:?}", doc.select(&sel).next());
}
```

Output is `None` :(

**Comment by causal-agent** [comment]
`r#"<a href="https://google.com""#` doesn't parse, it's missing the `>`.

**Comment by aCLr** [comment]
yeap, my fault. everything works fine. thank you.
