### ISSUE TITLE
HTML serialization is not deterministic.

### ISSUE THREAD

**Issue by moulins** [causal-agent/scraper#54]
The `scraper::node::Element` struct uses an `HashMap` to store the list of attributes, which means that the attribute order is not preserved, and that serializing an `Element` is not deterministic.

An easy fix for this would be to use an `IndexMap` for storing attributes in `Element`s.

Having deterministic serialization is pretty useful for things like unit tests, so this would be a welcome change.

**Comment by SirWindfield** [comment]
Would you be fine with this being an opt-in feature flag?

**Comment by moulins** [comment]
If this doesn't cause issues on your end, this would be enough. ;)

**Comment by nathaniel-daniel** [comment]
Maybe a [`BTreeMap`](https://doc.rust-lang.org/std/collections/struct.BTreeMap.html) could be used instead to avoid the extra dep?

**Comment by SirWindfield** [comment]
I totally forgot about the PR! I already did implement this with a BTreeMap! I just forgot to merge it.
