### ISSUE TITLE
selector accidently edited html

### ISSUE THREAD

**Issue by GopherJ** [causal-agent/scraper#57]
I'm writing a robot to fetch cn.etherscan.com's token data.

On their site the `transfers` section has content: `939,005`

![image](https://user-images.githubusercontent.com/33961674/107123779-7f219a80-68da-11eb-9878-e6c66a71b9b2.png)

while using the following code it gives me different thing:

```rust
    let transfers_selector = Selector::parse(
        ".card .card-body #ContentPlaceHolder1_trNoOfTxns #totaltxns",
    )
    .unwrap();

    if let Some(overview) =
        fragment.select(&overview_selector).next()
    {
        dbg!(&overview
            .select(&transfers_selector)
            .next()
            .unwrap()
            .html());
    }
```

![image](https://user-images.githubusercontent.com/33961674/107123841-e6d7e580-68da-11eb-8283-90fa86ab5627.png)

**Comment by GopherJ** [comment]
you can see `939,005` has been changed to `-`

**Comment by demurgos** [comment]
Does the raw HTML (before parsing it) contain `-` or `939,005`? It may be that the value you want is not set by the server but defined by JS on the client side. In such case, scaper can't do much more.

**Comment by GopherJ** [comment]
@demurgos Hi the raw HTML doesn't contain `-` but it contains `939,005`

**Comment by nathaniel-daniel** [comment]
@GopherJ The client js mutates that variable so you can't access it with `scraper`. The following example:
```rust
fn main() {
    let response =
        ureq::get("https://cn.etherscan.com/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52")
            .call()
            .expect("invalid http response");
    let response_text = response.into_string().expect("failed to get response text");
    let fragment = scraper::Html::parse_document(&response_text);

    let overview_selector = scraper::Selector::parse("#ContentPlaceHolder1_divSummary").expect("invalid overview selector");

    let transfers_selector =
        scraper::Selector::parse(".card .card-body #ContentPlaceHolder1_trNoOfTxns #totaltxns")
            .expect("invalid transfers selector");

    if let Some(overview) = fragment.select(&overview_selector).next() {
        dbg!(&overview.select(&transfers_selector).next().unwrap().html());
    }
}
``` 
yields 
```
[src\main.rs:16] &overview.select(&transfers_selector).next().unwrap().html() = "<span id=\"totaltxns\">-</span>"
```

Here's a version that does what you want by extracting the needed variables from js with regexes. Cargo

**Comment by GopherJ** [comment]
Yes I agree it's probably this
