### ISSUE TITLE
Consider exporting common errors thrown by this crate

### ISSUE THREAD

**Issue by moka491** [causal-agent/scraper#60]
Some returned `Result`s returned by scraper functions use error types from the `cssparser` crate.
Unfortunately in my project, I cannot handle them (e.g. using `thiserror`) without adding `cssparser` to my dependencies as well, even though I don't need it anywhere else.

~~Please consider reexporting cssparser, or alternatively define error types for the scraper crate and export those.~~

Let's define a common error struct for `scraper` so that crates using it can integrate it in their error handling.

**Comment by SirWindfield** [comment]
The better approach would probably be to define error types in `scraper` itself and export those.

**Comment by moka491** [comment]
Sounds good, yeah. It solves the same issue, so feel free to see this as the solution of this ticket.

**Comment by cfvescovo** [comment]
This is now being addressed in PR #95.
Thanks to @Kiwifruit
