### ISSUE TITLE
Cannot parse "frame"

### ISSUE THREAD

**Issue by panpur** [causal-agent/scraper#65]
Hello,

Following code cannot find `frame` using scrapper 0.12.0
```
let fragment = Html::parse_fragment("<frameset><frame src='src1'></frameset>");
let selector = Selector::parse("frame").unwrap();
fragment.select(&selector).next().unwrap();
```
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

Am I missing something?

Thanks

**Comment by nathaniel-daniel** [comment]
This might be because the HTML string is invalid. I'm not sure if that's a bug since trying do do something similar in js/html also doesn't work:
```js
document.body.innerHTML = "<frameset><frame src='src1'></frameset>";
```

I was able to get this particular example to work though by using `Html::parse_document` instead.

**Comment by panpur** [comment]
Yeah, it appears that frameset is obsolete.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frameset
Thanks
