### ISSUE TITLE
Self closing elements are not rendered correct

### ISSUE THREAD

**Issue by emirror-de** [causal-agent/scraper#72]
Dear maintainer,

I just tried to serialize a `<br>` tag by creating the according `Node`, appending it to a root node of a `Html` and call `root_element().html()` on it.

But the result gives me `<br></br>`.

Is this intended? Or do I need to set some configuration options for the serialization to make this serialize to `<br>`?

Best regards,
Lewin

**Comment by causal-agent** [comment]
> I just tried to serialize a <br> tag by creating the according Node, appending it to a root node of a Html and call root_element().html() on it.
> 
> But the result gives me <br></br>.
> 
> Is this intended? Or do I need to set some configuration options for the serialization to make this serialize to <br>?

The node needs to be in the `html` namespace: https://docs.rs/html5ever/0.25.1/src/html5ever/serialize/mod.rs.html#169

**Comment by emirror-de** [comment]
Damn, I missed that! Thanks for the super fast response!
