### ISSUE TITLE
Bump html5ever for removed time methods

### ISSUE THREAD

**Issue by bigpick** [causal-agent/scraper#74]
# Bug Info
The current of version of html5ever is utilizing sinnce-removed method (`precise_time_ns`):
* https://github.com/servo/html5ever/pull/453
* https://github.com/time-rs/time/blob/main/CHANGELOG.md#removed
   > ## Removed
   > v0.1 APIs, previously behind an enabled-by-default feature flag
   > ...
   > * precise_time_ns

```
error[E0425]: cannot find function `precise_time_ns` in crate `time`
   --> ...../cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.5.4/src/macros.rs:27:26
    |
27  |         let t0 = ::time::precise_time_ns();
    |                          ^^^^^^^^^^^^^^^ not found in `time`
    |
   ::: ...../.cargo/registry/src/github.com-1ecc6299db9ec823/html5ever-0.5.4/src/tokenizer/mod.rs:230:27
    |
230 |             let (_, dt) = time!(self.sink.process_token(token));
    |                           ------------------------------------- in this macro invocation
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

---

edit: looks like

```
html5ever = "0.25.1"
```

is still currently the latest published release of `html5ever` still :\

**Comment by cfvescovo** [comment]
We will have to wait for a new version of html5ever to be published. The latest version available on crates.io (at the time of writing, 20220221) is 0.25.1 and was published 2 years ago.

Maybe we should open an issue on servo/html5ever and ask for a new release to be published.

**Comment by cfvescovo** [comment]
html5ever 0.26.0 is out!

**Comment by cfvescovo** [comment]
I will check if they have made any breaking changes and report back here

**Comment by cfvescovo** [comment]
All OK, html5ever bumped to 0.26 in https://github.com/causal-agent/scraper/commit/1509a6414ede046519f26744b64ecc0bd119fe02
