### ISSUE TITLE
Error using scraper in spawned process via Tokio runtime

### ISSUE THREAD

**Issue by Randall-Coding** [causal-agent/scraper#75]
Environment: 
 - Linux 
 - Rust 1.60.0-nightly
 - Scraper 0.12.0
 
Problem: 

  When calling `rt.spawn(my_job::run(...));` I receive these compile errors 

> generator cannot be sent between threads safely
> within `ego_tree::Node<scraper::node::Node>`, the trait `Sync` is not implemented for `Cell<NonZeroUsize>`rustc
> [mod.rs(381, 25): ]()required by a bound in `Runtime::spawn`
> generator cannot be sent between threads safely
> within `ego_tree::Node<scraper::node::Node>`, the trait `Sync` is not implemented for `UnsafeCell<tendril::tendril::Buffer>`rustc
> [mod.rs(381, 25): ]()required by a bound in `Runtime::spawn`
> generator cannot be sent between threads safely
> within `ego_tree::Node<scraper::node::Node>`, the trait `Sync` is not implemented for `*mut tendril::fmt::UTF8`rustc
> [mod.rs(381, 25): ]()required by a bound in `Runtime::spawn`
> generator cannot be sent between threads safely
> within `ego_tree::Node<scraper::node::Node>`, the trait `Sync` is not implemented for `Cell<tendril::tendril::PackedUsize>`rustc
> [mod.rs(381, 25): ]()required by a bound in `Runtime::spawn`

UPDATE: The error only appears when I run this code within `my_job.rs`.

`download::run(...).await.unwrap();`  

If I remove that line everything compiles.  Can someone explain why?

Code: 

main.rs
``` 
use tokio::runtime::Runtime;
...
let mut rt = Runtime::new().unwrap();
rt.spawn(my_job::run(...))
```

my_job.rs 
``` 
let title_selector = scraper::Selector::parse("title").unwrap();
let title = document.select(&title_selector).next().unwrap().inner_html();
download::run("", "./Downloads", "").await.unwrap();
```

Question: 

It appears scraper might not be thread safe according to Rust compiler.  Are there any work arounds to this so I can still use scraper crate?

**Comment by adumbidiot** [comment]
Try [`spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) while parsing. A document cannot be sent between threads.

**Comment by Randall-Coding** [comment]
> Try [`spawn_blocking`](https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html) while parsing. A document cannot be sent between threads.

I will look into `spawn_blocking`.  However, I don't really see the part where my document is being passed anywhere.  I'm simply running another process after parsing, and not (to my knowledge) passing the document around.

**Comment by Randall-Coding** [comment]
**Solution**:    For some reason when I call `download::run("", "./Downloads", "").await.unwrap();` tokio is moving everything from the calling context into the new thread in some way.  I didn't know threads worked that way, but that is the only conclusion I can come to considering the solution.

The solution is to do my business with scraper inside of a closure, ensuring all the scraper class instances are dropped before calling + waiting for the `download::run` async function and just returning the strings I want scraped from the html.  

```
let x =|| -> (String, String){
  let document = scraper::Html::parse_document(&html);
  ... parse things...
  (final_url, title)
};
```

If anyone has an explanation for why tokio does what it does that would ease my troubled mind.  Feeling very Rustrated with the whole situation :face_with_spiral_eyes:

**Comment by adumbidiot** [comment]
Using `await` will send any un-dropped variables between threads. There's also a limitation in lifetime analysis where you cannot just use `drop` on variables in futures to drop them before `await` points; you need to create a new scope with `{` and `}` and perform all operations on variables you don't want to keep between `await` points there. 

`spawn_blocking` runs a function, not a future. It's intended to run blocking operations on a background threadpool, like parsing, to avoid blocking the runtime. It returns a future you can `await` on to get back a response from that function. 

I believe `tokio` futures are required to be threadsafe as it can run as a multithreaded runtime; when you await, the future may be executed by another thread. As a result, you cannot carry non-threadsafe variables across `await` points.

**Comment by Randall-Coding** [comment]
Thanks for the suggestions and input.  I will try using just a new scope instead of the closure.  

Where do you learn all this stuff about tokio by the way?  Is there a book on it?  Come to think of it I still need to read through the Rust book itself, but recently I've preferred learning by doing (which has it's drawbacks at times).

**Comment by adumbidiot** [comment]
The `tokio` website has a nice [tutorial section](https://tokio.rs/tokio/tutorial). The rest you can generally pick up by reading the api docs.

**Comment by cfvescovo** [comment]
@adumbidiot Great job! 

@Randall-Coding Since it seems it's all good now I am closing this issue. Let me know if you're still having issues and I will reopen it asap.
