### ISSUE TITLE
selector can't match 'body'

### ISSUE THREAD

**Issue by TsuITOAR** [causal-agent/scraper#79]
Hi, I'm trying to match in something like this
```html
<article class="out">
    <body>
        <article class="in">
            
        </article>
    </body>
</article>
```

with code
```rs
use scraper::{Html, Selector};

type Result<O> = std::result::Result<O, Box<dyn std::error::Error>>;

const HTML: &str = r#"
<article class="out">
    <body>
        <article class="in">
            
        </article>
    </body>
</article>
"#;

fn main() -> Result<()> {
    let html: Html = Html::parse_document(HTML);
    let selector = Selector::parse(r" article > body > article").unwrap();
    html.select(&selector).for_each(|x| println!("\n-----\n{}\n-----\n", x.html()));

    Ok(())
}

```

` article > body > article` can't match anything

but `article > article` output

```
-----
<article class="in">
        </article>
-----
```

`parse_document` and `parse_fragment` give the same results.

**Comment by TsuITOAR** [comment]
> `<body>` isn't valid anywhere but as the second child of `<html>` so the HTML parser is dropping it

Maybe selector should drop it while parsing to match this situation? The content is the response to an api call in loading a dynamic webpage, which should be quite common.

**Comment by causal-agent** [comment]
Neither is up to scraper. It's behaving as a browser would
