### ISSUE TITLE
Selector doesn't work properly

### ISSUE THREAD

**Issue by nerdunit** [causal-agent/scraper#80]
Selector doesn't work with any of these patterns which are valid xpaths, the .unwrap() doesn't fail but it find 0 matches

p[class="tmp-image"]
p>img

**Comment by nerdunit** [comment]
Also normal p doesn't return all the p's in the page

**Comment by nerdunit** [comment]
Apparently the crate doesn't check inside <noscript> tags, doing body = body.replace("<noscript>","").replace("</noscript>",""); fixed this, maybe fix in a next release?

**Comment by causal-agent** [comment]
issues need actual examples to reproduce the problem
