### ISSUE TITLE
Cut a new release

### ISSUE THREAD

**Issue by teymour-aldridge** [causal-agent/scraper#88]
Clicked the enter key too early (oops)!

cc @cfvescovo we should try to cut a new release (probably v0.14) at some point (we don't have many changes, but as they are stable it makes sense to push them to crates.io in my view).

I would make a release, but I don't have permissions to publish on crates.io (I think)

**Comment by causal-agent** [comment]
@teymour-aldridge I've invited you to be an owner on crates.io

**Comment by cfvescovo** [comment]
Maybe we should start planning for the next release.
Are there any issues you would like to see closed before 0.14 is released?

**Comment by cfvescovo** [comment]
Maybe we should work on #45 and #60.

#45: we could consider switching to strings (or something else) instead of LocalNames and use a faster HashSets implementation to improve performance.

#60: we could define our own error types and export them

**Comment by cfvescovo** [comment]
@teymour-aldridge Yesterday I forgot to tag you

**Comment by cfvescovo** [comment]
Now #60 is resolved. Should I create a new release? @teymour-aldridge

**Comment by cfvescovo** [comment]
Done: https://github.com/causal-agent/scraper/commit/24baef86a241a32577206ad544ec9595daad3342
Uploaded to [crates.io](https://crates.io/crates/scraper/0.14.0)

**Comment by causal-agent** [comment]
@cfvescovo @teymour-aldridge thanks for your work on this!
