### ISSUE TITLE
Dependency `selectors` is not on the last version

### ISSUE THREAD

**Issue by Elrendio** [causal-agent/scraper#89]
Current version used: 0.22
Last version: 0.23

Seems like just bump the version won't make a breaking change. A good practice is also to re-export the crate `selectors` to avoid users having to guess which version they should be using 😊

**Comment by cfvescovo** [comment]
@teymour-aldridge you're right.

I tried updating selectors but there was a compatibility issue with css-parser.

**Comment by cfvescovo** [comment]
@Elrendio if you have a patch feel free to open a PR. I will happily review it.

**Comment by cfvescovo** [comment]
We cannot fix this right now because a refactor would be needed to update `selectors`. As I am not sure on what approach should be taken (we could either refactor to support the latest version of selectors or remove `LocalNames` completely), I set this as wontfix for now

**Comment by cfvescovo** [comment]
Solved in #99
