### ISSUE TITLE
Vagueness is variable names and documentation make this a liability to use

### ISSUE THREAD

**Issue by Johnrobmiller** [causal-agent/scraper#92]
Throughout the entire api and documentation, the unanimous use of vague variable names combined with sparse documentation makes this library a liability to use since any codebase that uses this library will inherent at least some of its vagueness, weakening the codebase.

Please consider doing a refactor of both variable names and documentation with the goal of improving clarity and precision.

**Comment by causal-agent** [comment]
> Vagueness is variable names and documentation make this a liability to use

then don't use it. and don't open unhelpful issues on it either.

please consider doing a refactor of how you attempt to communicate with strangers on the internet.
