### ISSUE TITLE
NodeRef<Node> to ElementRef so that it can be selected from?

### ISSUE THREAD

**Issue by raine** [causal-agent/scraper#93]
Hey! For the life of me I can't figure out how to select from children of a `ElementRef`.

```rs
for node in elem.children() {
   // node is type of `NodeRef<Node>` and has no select method, nor does there appear to be anyway to make an `ElementRef` out of it.
}
```

Any ideas? Thanks!

**Comment by causal-agent** [comment]
https://docs.rs/scraper/latest/scraper/element_ref/struct.ElementRef.html#method.wrap

**Comment by raine** [comment]
Thanks! `wrap` ended up working after all.
